export const SET_GRID = "SET_GRID";
export const CHANGE_DIFFICULTY_LEVEL = "CHANGE_DIFFICULTY_LEVEL";
export const CHANGE_SCORE = "CHANGE_SCORE";
export const GAME_OVER = "GAME_OVER";
export const RESET_MINE_MARKER = "RESET_MINE_MARKER";
export const MINE_MARKED = "MINE_MARKED";
export const CHANGE_TOTAL_MINES = "CHANGE_TOTAL_MINES";
export const CHANGE_LEVELS = "CHANGE_LEVELS";